# Generated by Django 3.2.13 on 2022-06-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_tasklist_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
