# Generated by Django 3.2.13 on 2022-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_auto_20220616_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
